import Head from 'next/head';
import App from '../_app';

import Editor from "./Editor";

export default function Index() {
    return (
        <>
            <Head>
                <title>Struc Editor</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <App Component={Editor}></App>
        </>
    )
}