[package]
name = "fasing"
version = "0.1.0"
edition = "2021"


[dependencies]
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"

euclid = { version = "0.22", features = ["serde"] }


[build-dependencies]
serde_json = "1.0"

anyhow = "1.0"