[package]
name = "fasing-editor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.9"
pollster = "0.2"
anyhow = "1.0"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

wgpu = "0.13"
winit = "0.27"

egui = { version = "0.19", features = [ "serde" ] }
egui-winit = "0.19"
egui-wgpu = "0.19"
